### ISSUE TITLE
Broken link on crates.io

### ISSUE THREAD

**Issue by jimvdl** [BeaconBrigade/lcp-sim#22]
Hi! 

The link to the source of `chem-eq` that crates.io displays on the right seems to be broken; the issue seems to come from the `homepage` attribute in `Cargo.toml` (I believe you are missing a /src-tauri/). I wanted to bring this to your attention because I like to view source code on GitHub and had to do a little digging to find it.

P.S. I just have to say that this crate is extremely well written, the code quality is _very_ high 👍🏻 Well done!

**Comment by BeaconBrigade** [comment]
Hey! Thanks for the letting me know. I refactored the project recently to use tauri and forgot to update the link :). I also have some breaking changes with new features that I've just haven't got around to publishing since I've been distracted by the main project. I'll update that now. 

Thanks for the compliments, `chem-eq` was probably my favourite part of this whole project and spent entirely too much time on it for features that I didn't really need :) Glad it could be interesting or useful to somebody!

The link should be fixed in 4fbf69fb4c6e91e88ab7a021cd528e5bdae96553 and the new release on [crates.io](https://crates.io/crates/chem-eq/0.3.0)

**Comment by jimvdl** [comment]
Awesome! Glad I could be of some assistance. 

On the second note; no problem! I tend to look through source code of crates that I want to use because I'm always curious to see how they are built and I was pleasantly surprised about the amount of polish you gave `chem-eq` :)

Keep up the great work!
